In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('//content/drive/MyDrive/zomato_cleaned.csv')

In [4]:
df.shape

(38964, 22)

In [5]:
df.head(5)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),distance_km,delivery_speed
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,...,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46,10.280582,Slow
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,...,High,1,Meal,motorcycle,1.0,No,Metropolitian,23,6.242319,Average
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,...,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21,13.787860,Average
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,...,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20,2.930258,Average
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,...,Jam,1,Snack,scooter,1.0,No,Metropolitian,41,19.396618,Slow

In [6]:
df.tail(5)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),distance_km,delivery_speed
38959,0x1178,RANCHIRES16DEL01,35.0,4.2,23.371292,85.327872,23.481292,85.437872,08-03-2022,21:45,...,Jam,2,Drinks,motorcycle,1.0,No,Metropolitian,33,16.600272,Average
38960,0x7c09,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,24-03-2022,11:35,...,High,1,Meal,motorcycle,0.0,No,Metropolitian,32,1.489846,Average
38961,0x4f8d,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,11-03-2022,23:50,...,Low,1,Drinks,scooter,0.0,No,Metropolitian,16,4.657195,Fast
38962,0x5eee,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,07-03-2022,13:35,...,High,0,Snack,motorcycle,1.0,No,Metropolitian,26,6.232393,Average
38963,0x5fb2,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,02-03-2022,17:10,...,Medium,2,Snack,scooter,1.0,No,Metropolitian,36,12.074396,Slow

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38964 entries, 0 to 38963
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           38964 non-null  object
 1   Delivery_person_ID           38964 non-null  object
 2   Delivery_person_Age          37945 non-null  float64
 3   Delivery_person_Ratings      37909 non-null  float64
 4   Restaurant_latitude          38964 non-null  float64
 5   Restaurant_longitude         38964 non-null  float64
 6   Delivery_location_latitude   38964 non-null  float64
 7   Delivery_location_longitude  38964 non-null  float64
 8   Order_Date                   38964 non-null  object
 9   Time_Orderd                  38129 non-null  object
 10  Time_Order_picked            38964 non-null  object
 11  Weather_conditions           38964 non-null  object
 12  Road_traffic_density         38964 non-null  object
 13  Vehicle_condition            38964 non-null  int64
 14  Type_of_order                38964 non-null  object
 15  Type_of_vehicle              38964 non-null  object
 16  multiple_deliveries          38964 non-null  float64
 17  Festival                     38964 non-null  object
 18  City                         38964 non-null  object
 19  Time_taken (min)             38964 non-null  int64
 20  distance_km                  38964 non-null  float64
 21  delivery_speed               38964 non-null  object
dtypes: float64(8), int64(2), object(12)
memory usage: 6.5+ MB

In [8]:
df.columns

Index(['ID', 'Delivery_person_ID', 'Delivery_person_Age',
       'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weather_conditions', 'Road_traffic_density',
       'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City', 'Time_taken (min)',
       'distance_km', 'delivery_speed'],
      dtype='object')

In [9]:
df.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age            1019
Delivery_person_Ratings        1055
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                     835
Time_Order_picked                 0
Weather_conditions                0
Road_traffic_density              0
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries               0
Festival                          0
City                              0
Time_taken (min)                  0
distance_km                       0
delivery_speed                    0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
ID,38964,38964,0x5fb2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Delivery_person_ID,38964,1170,HYDRES04DEL02,64,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Delivery_person_Age,37945.0,NaN,NaN,NaN,29.607089,5.763202,20.0,25.0,30.0,35.0,39.0
Delivery_person_Ratings,37909.0,NaN,NaN,NaN,4.631879,0.317006,2.5,4.5,4.7,4.9,5.0
Restaurant_latitude,38964.0,NaN,NaN,NaN,18.915583,5.460635,9.957144,12.986047,19.065838,22.751234,30.914057
Restaurant_longitude,38964.0,NaN,NaN,NaN,76.914536,3.498179,72.768726,73.897902,76.618203,78.368855,88.433452
Delivery_location_latitude,38964.0,NaN,NaN,NaN,18.979545,5.462504,9.967144,13.066047,19.124049,22.820072,31.054057
Delivery_location_longitude,38964.0,NaN,NaN,NaN,76.978498,3.498357,72.778726,73.938972,76.663067,78.405467,88.563452
Order_Date,38964,44,15-03-2022,1031,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time_Orderd,38129,176,17:55,407,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time_Order_picked,38964,193,21:30,430,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Weather_conditions,38964,6,Fog,6660,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Road_traffic_density,38964,4,Low,13139,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vehicle_condition,38964.0,NaN,NaN,NaN,0.995534,0.817312,0.0,0.0,1.0,2.0,2.0
Type_of_order,38964,4,Snack,9815,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Type_of_vehicle,38964,3,motorcycle,22942,NaN,NaN,NaN,NaN,NaN,NaN,NaN
multiple_deliveries,38964.0,NaN,NaN,NaN,0.749589,0.572172,0.0,0.0,1.0,1.0,3.0
Festival,38964,2,No,38180,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,38964,3,Metropolitian,30036,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time_taken (min),38964.0,NaN,NaN,NaN,26.581511,9.339546,10.0,19.0,26.0,33.0,54.0
distance_km,38964.0,NaN,NaN,NaN,9.765092,5.605705,1.465067,4.658009,9.219906,13.68159,20.969489
delivery_speed,38964,3,Average,19982,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df.nunique().sort_values(ascending=False)

ID                             38964
Delivery_location_latitude      4352
Delivery_location_longitude     4352
distance_km                     4352
Delivery_person_ID              1170
Restaurant_longitude             388
Restaurant_latitude              388
Time_Order_picked                193
Time_Orderd                      176
Time_taken (min)                  45
Order_Date                        44
Delivery_person_Ratings           26
Delivery_person_Age               20
Weather_conditions                 6
Type_of_order                      4
Road_traffic_density               4
multiple_deliveries                4
Vehicle_condition                  3
City                               3
Type_of_vehicle                    3
delivery_speed                     3
Festival                           2
dtype: int64

In [13]:
for col in df.select_dtypes(include="object").columns:
    print("\n", col)
    print(df[col].value_counts())

 ID
ID
0x5fb2    1
0xcdcd    1
0xd987    1
0x2784    1
0x1b0d    1
         ..
0xc9cf    1
0x689b    1
0x3aab    1
0x3af3    1
0xdb64    1
Name: count, Length: 38964, dtype: int64

 Delivery_person_ID
Delivery_person_ID
HYDRES04DEL02       64
COIMBRES010DEL02    63
VADRES11DEL02       63
JAPRES14DEL02       63
RANCHIRES16DEL01    63
                    ..
BHPRES08DEL03        5
KOLRES07DEL03        5
DEHRES13DEL02        5
BHPRES010DEL03       5
KOCRES16DEL03        4
Name: count, Length: 1170, dtype: int64

 Order_Date
Order_Date
15-03-2022    1031
03-04-2022    1016
09-03-2022    1013
13-03-2022    1008
05-04-2022    1007
03-03-2022    1005
24-03-2022    1005
07-03-2022    1003
01-03-2022    1001
26-03-2022    1000
21-03-2022     997
19-03-2022     994
05-03-2022     990
01-04-2022     989
11-03-2022     987
28-03-2022     986
30-03-2022     980
17-03-2022     970
02-03-2022     889
02-04-2022     879
10-03-2022     878
16-03-2022     874
20-03-2022     873
06-03-2022     873
04-03-2022     866
29-03-2022     865
23-03-2022     861
18-03-2022     857
25-03-2022     856
12-03-2022     856
08-03-2022     855
31-03-2022     851
14-03-2022     850
27-03-2022     849
06-04-2022     840
04-04-2022     827
11-02-2022     734
17-02-2022     709
15-02-2022     705
13-02-2022     705
16-02-2022     672
18-02-2022     663
14-02-2022     648
12-02-2022     647
Name: count, dtype: int64

 Time_Orderd
Time_Orderd
17:55          407
21:55          402
19:50          401
21:15          399
18:35          396
              ...
13:25           49
12:25           48
16:30           45
13:20           44
0.666666667     41
Name: count, Length: 176, dtype: int64

 Time_Order_picked
Time_Order_picked
21:30    430
18:25    396
18:45    396
18:05    394
21:45    392
        ...
16:15     38
13:20     37
16:20     37
16:10     35
17:10     32
Name: count, Length: 193, dtype: int64

 Weather_conditions
Weather_conditions
Fog           6660
Stormy        6572
Cloudy        6563
Sandstorms    6489
Windy         6436
Sunny         6244
Name: count, dtype: int64

 Road_traffic_density
Road_traffic_density
Low       13139
Jam       12414
Medium     9556
High       3855
Name: count, dtype: int64

 Type_of_order
Type_of_order
Snack     9815
Meal      9774
Drinks    9751
Buffet    9624
Name: count, dtype: int64

 Type_of_vehicle
Type_of_vehicle
motorcycle          22942
scooter             12926
electric_scooter     3096
Name: count, dtype: int64

 Festival
Festival
No     38180
Yes      784
Name: count, dtype: int64

 City
City
Metropolitian    30036
Urban             8782
Semi-Urban         146
Name: count, dtype: int64

 delivery_speed
delivery_speed
Average    19982
Fast       10164
Slow        8818
Name: count, dtype: int64

In [14]:
df["Time_taken (min)"].describe()

count    38964.000000
mean        26.581511
std          9.339546
min         10.000000
25%         19.000000
50%         26.000000
75%         33.000000
max         54.000000
Name: Time_taken (min), dtype: float64

In [15]:
df["delivery_speed"].value_counts(normalize=True) * 100

delivery_speed
Average    51.283236
Fast       26.085617
Slow       22.631147
Name: proportion, dtype: float64

In [16]:
df.nunique().sort_values(ascending=False)

ID                             38964
Delivery_location_latitude      4352
Delivery_location_longitude     4352
distance_km                     4352
Delivery_person_ID              1170
Restaurant_longitude             388
Restaurant_latitude              388
Time_Order_picked                193
Time_Orderd                      176
Time_taken (min)                  45
Order_Date                        44
Delivery_person_Ratings           26
Delivery_person_Age               20
Weather_conditions                 6
Type_of_order                      4
Road_traffic_density               4
multiple_deliveries                4
Vehicle_condition                  3
City                               3
Type_of_vehicle                    3
delivery_speed                     3
Festival                           2
dtype: int64

In [17]:
for col in df.select_dtypes(include="object").columns:
    print("\n", col)
    print(df[col].value_counts())

 ID
ID
0x5fb2    1
0xcdcd    1
0xd987    1
0x2784    1
0x1b0d    1
         ..
0xc9cf    1
0x689b    1
0x3aab    1
0x3af3    1
0xdb64    1
Name: count, Length: 38964, dtype: int64

 Delivery_person_ID
Delivery_person_ID
HYDRES04DEL02       64
COIMBRES010DEL02    63
VADRES11DEL02       63
JAPRES14DEL02       63
RANCHIRES16DEL01    63
                    ..
BHPRES08DEL03        5
KOLRES07DEL03        5
DEHRES13DEL02        5
BHPRES010DEL03       5
KOCRES16DEL03        4
Name: count, Length: 1170, dtype: int64

 Order_Date
Order_Date
15-03-2022    1031
03-04-2022    1016
09-03-2022    1013
13-03-2022    1008
05-04-2022    1007
03-03-2022    1005
24-03-2022    1005
07-03-2022    1003
01-03-2022    1001
26-03-2022    1000
21-03-2022     997
19-03-2022     994
05-03-2022     990
01-04-2022     989
11-03-2022     987
28-03-2022     986
30-03-2022     980
17-03-2022     970
02-03-2022     889
02-04-2022     879
10-03-2022     878
16-03-2022     874
20-03-2022     873
06-03-2022     873
04-03-2022     866
29-03-2022     865
23-03-2022     861
18-03-2022     857
25-03-2022     856
12-03-2022     856
08-03-2022     855
31-03-2022     851
14-03-2022     850
27-03-2022     849
06-04-2022     840
04-04-2022     827
11-02-2022     734
17-02-2022     709
15-02-2022     705
13-02-2022     705
16-02-2022     672
18-02-2022     663
14-02-2022     648
12-02-2022     647
Name: count, dtype: int64

 Time_Orderd
Time_Orderd
17:55          407
21:55          402
19:50          401
21:15          399
18:35          396
              ...
13:25           49
12:25           48
16:30           45
13:20           44
0.666666667     41
Name: count, Length: 176, dtype: int64

 Time_Order_picked
Time_Order_picked
21:30    430
18:25    396
18:45    396
18:05    394
21:45    392
        ...
16:15     38
13:20     37
16:20     37
16:10     35
17:10     32
Name: count, Length: 193, dtype: int64

 Weather_conditions
Weather_conditions
Fog           6660
Stormy        6572
Cloudy        6563
Sandstorms    6489
Windy         6436
Sunny         6244
Name: count, dtype: int64

 Road_traffic_density
Road_traffic_density
Low       13139
Jam       12414
Medium     9556
High       3855
Name: count, dtype: int64

 Type_of_order
Type_of_order
Snack     9815
Meal      9774
Drinks    9751
Buffet    9624
Name: count, dtype: int64

 Type_of_vehicle
Type_of_vehicle
motorcycle          22942
scooter             12926
electric_scooter     3096
Name: count, dtype: int64

 Festival
Festival
No     38180
Yes      784
Name: count, dtype: int64

 City
City
Metropolitian    30036
Urban             8782
Semi-Urban         146
Name: count, dtype: int64

 delivery_speed
delivery_speed
Average    19982
Fast       10164
Slow        8818
Name: count, dtype: int64

In [18]:
df["Time_taken (min)"].describe()

count    38964.000000
mean        26.581511
std          9.339546
min         10.000000
25%         19.000000
50%         26.000000
75%         33.000000
max         54.000000
Name: Time_taken (min), dtype: float64

In [19]:
df["distance_km"].describe()

count    38964.000000
mean         9.765092
std          5.605705
min          1.465067
25%          4.658009
50%          9.219906
75%         13.681590
max         20.969489
Name: distance_km, dtype: float64

In [20]:
df["delivery_speed"].value_counts(normalize=True) * 100

delivery_speed
Average    51.283236
Fast       26.085617
Slow       22.631147
Name: proportion, dtype: float64

In [21]:
numeric_cols = [
    "Delivery_person_Age",
    "Delivery_person_Ratings",
    "Vehicle_condition",
    "multiple_deliveries",
    "distance_km",
    "Time_taken (min)"
]
outlier_report = []

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = ((df[col] < lower) | (df[col] > upper)).sum()

    outlier_report.append({
        "Column": col,
        "Lower_Bound": lower,
        "Upper_Bound": upper,
        "Outlier_Count": outliers,
        "Outlier_%": round(outliers / len(df) * 100, 2)
    })

outlier_report = pd.DataFrame(outlier_report)

outlier_report

                    Column  Lower_Bound  Upper_Bound  Outlier_Count  Outlier_%
0      Delivery_person_Age    10.000000    50.000000              0       0.00
1  Delivery_person_Ratings     3.900000     5.500000           1024       2.63
2        Vehicle_condition    -3.000000     5.000000              0       0.00
3      multiple_deliveries    -1.500000     2.500000            313       0.80
4              distance_km    -8.877362    27.216962              0       0.00
5         Time_taken (min)    -2.000000    54.000000              0       0.00

In [22]:
df["Delivery_person_Ratings"].describe()

count    37909.000000
mean         4.631879
std          0.317006
min          2.500000
25%          4.500000
50%          4.700000
75%          4.900000
max          5.000000
Name: Delivery_person_Ratings, dtype: float64

In [23]:
df["Delivery_person_Ratings"].value_counts().sort_index()

Delivery_person_Ratings
2.5      18
2.6      19
2.7      20
2.8      17
2.9      18
3.0       5
3.1      25
3.2      26
3.3      23
3.4      30
3.5     228
3.6     187
3.7     197
3.8     211
3.9     169
4.0     954
4.1    1279
4.2    1291
4.3    1258
4.4    1191
4.5    2865
4.6    6012
4.7    6124
4.8    6172
4.9    6109
5.0    3461
Name: count, dtype: int64

In [24]:
df["multiple_deliveries"].value_counts(dropna=False).sort_index()

multiple_deliveries
0.0    12165
1.0    24704
2.0     1782
3.0      313
Name: count, dtype: int64

In [25]:
df["Delivery_person_Ratings"].describe()

count    37909.000000
mean         4.631879
std          0.317006
min          2.500000
25%          4.500000
50%          4.700000
75%          4.900000
max          5.000000
Name: Delivery_person_Ratings, dtype: float64

In [26]:
df["multiple_deliveries"].value_counts(dropna=False).sort_index()

multiple_deliveries
0.0    12165
1.0    24704
2.0     1782
3.0      313
Name: count, dtype: int64

In [27]:
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)

missing_report = pd.DataFrame({
    "Missing_Count": missing,
    "Missing_Percentage": missing_pct
})

missing_report[missing_report["Missing_Count"] > 0]

                         Missing_Count  Missing_Percentage
Delivery_person_Age               1019                2.62
Delivery_person_Ratings           1055                2.71
Time_Orderd                        835                2.14

In [28]:
df["Delivery_person_Age"].describe()

count    37945.000000
mean        29.607089
std          5.763202
min         20.000000
25%         25.000000
50%         30.000000
75%         35.000000
max         39.000000
Name: Delivery_person_Age, dtype: float64

In [29]:
df["Delivery_person_Ratings"].describe()

count    37909.000000
mean         4.631879
std          0.317006
min          2.500000
25%          4.500000
50%          4.700000
75%          4.900000
max          5.000000
Name: Delivery_person_Ratings, dtype: float64

In [30]:
df["Time_Orderd"].head(20)

0     21:55
1     14:55
2     17:30
3     09:20
4     19:50
5     20:25
6     14:55
7     20:30
8     21:15
9     20:20
10    22:30
11    08:15
12    19:30
13    12:25
14    18:35
15    20:35
16    23:20
17    21:20
18    23:35
19    22:35
Name: Time_Orderd, dtype: object

In [31]:
df["Time_Orderd"].value_counts(dropna=False).head(20)

Time_Orderd
NaN            835
17:55          407
21:55          402
19:50          401
21:15          399
18:35          396
19:55          394
0.833333333    388
21:35          385
22:20          384
21:20          384
17:40          383
18:10          381
22:45          381
22:10          377
20:40          376
21:40          376
20:50          376
20:35          375
17:35          375
Name: count, dtype: int64

In [32]:
numeric_cols = [
    "Delivery_person_Age",
    "Delivery_person_Ratings",
    "Vehicle_condition",
    "multiple_deliveries",
    "distance_km",
    "Time_taken (min)"
]

In [33]:
df["delivery_speed"].dtype
df["delivery_speed"].head(20)

0        Slow
1     Average
2     Average
3     Average
4        Slow
5     Average
6     Average
7        Slow
8        Fast
9        Slow
10    Average
11    Average
12       Slow
13       Slow
14       Fast
15       Fast
16       Slow
17       Slow
18       Fast
19    Average
Name: delivery_speed, dtype: object

In [34]:
df["delivery_speed"].unique()[:20]

array(['Slow', 'Average', 'Fast'], dtype=object)

In [35]:
pd.to_numeric(..., errors="coerce")

Ellipsis

In [36]:
df_clean = df.copy()

In [37]:
df_clean["Time_Orderd"] = pd.to_datetime(
    df_clean["Time_Orderd"],
    format="%H:%M",
    errors="coerce"
)

In [38]:
df_clean["Time_Orderd"].isnull().sum()

np.int64(4345)

In [39]:
df_clean.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age            1019
Delivery_person_Ratings        1055
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    4345
Time_Order_picked                 0
Weather_conditions                0
Road_traffic_density              0
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries               0
Festival                          0
City                              0
Time_taken (min)                  0
distance_km                       0
delivery_speed                    0
dtype: int64

In [40]:
df_clean = df.copy()

In [41]:
df_clean["Delivery_person_Age"] = (
    df_clean["Delivery_person_Age"]
    .fillna(df_clean["Delivery_person_Age"].median())
)

In [42]:
df_clean["Delivery_person_Age"].isnull().sum()

np.int64(0)

In [43]:
df_clean["Delivery_person_Ratings"] = (
    df_clean["Delivery_person_Ratings"]
    .fillna(df_clean["Delivery_person_Ratings"].median())
)

In [44]:
df_clean["Delivery_person_Ratings"].isnull().sum()

np.int64(0)

In [45]:
df_clean["Time_Orderd"] = pd.to_datetime(
    df_clean["Time_Orderd"],
    format="%H:%M",
    errors="coerce"
)

In [46]:
df_clean.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age               0
Delivery_person_Ratings           0
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    4345
Time_Order_picked                 0
Weather_conditions                0
Road_traffic_density              0
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries               0
Festival                          0
City                              0
Time_taken (min)                  0
distance_km                       0
delivery_speed                    0
dtype: int64

In [47]:
df_clean["Order_Date"] = pd.to_datetime(
    df_clean["Order_Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [48]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38964 entries, 0 to 38963
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           38964 non-null  object
 1   Delivery_person_ID           38964 non-null  object
 2   Delivery_person_Age          38964 non-null  float64
 3   Delivery_person_Ratings      38964 non-null  float64
 4   Restaurant_latitude          38964 non-null  float64
 5   Restaurant_longitude         38964 non-null  float64
 6   Delivery_location_latitude   38964 non-null  float64
 7   Delivery_location_longitude  38964 non-null  float64
 8   Order_Date                   38964 non-null  datetime64[ns]
 9   Time_Orderd                  34619 non-null  datetime64[ns]
 10  Time_Order_picked            38964 non-null  object
 11  Weather_conditions           38964 non-null  object
 12  Road_traffic_density         38964 non-null  object
 13  Vehicle_condition            38964 non-null  int64
 14  Type_of_order                38964 non-null  object
 15  Type_of_vehicle              38964 non-null  object
 16  multiple_deliveries          38964 non-null  float64
 17  Festival                     38964 non-null  object
 18  City                         38964 non-null  object
 19  Time_taken (min)             38964 non-null  int64
 20  distance_km                  38964 non-null  float64
 21  delivery_speed               38964 non-null  object
dtypes: datetime64[ns](2), float64(8), int64(2), object(10)
memory usage: 6.5+ MB

In [49]:
df_clean.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age               0
Delivery_person_Ratings           0
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    4345
Time_Order_picked                 0
Weather_conditions                0
Road_traffic_density              0
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries               0
Festival                          0
City                              0
Time_taken (min)                  0
distance_km                       0
delivery_speed                    0
dtype: int64

In [50]:
df_clean["Day_Name"] = df_clean["Order_Date"].dt.day_name()

In [51]:
df_clean["Month"] = df_clean["Order_Date"].dt.month_name()

In [52]:
df_clean["Day"] = df_clean["Order_Date"].dt.day

In [53]:
df_clean["Is_Weekend"] = df_clean["Day_Name"].isin(
    ["Saturday", "Sunday"]
)

In [54]:
df_clean["Order_Hour"] = df_clean["Time_Orderd"].dt.hour

In [55]:
def time_of_day(hour):
    if pd.isna(hour):
        return "Unknown"
    elif 6 <= hour < 12:
        return "Morning"
    elif 12 <= hour < 17:
        return "Afternoon"
    elif 17 <= hour < 21:
        return "Evening"
    else:
        return "Night"

df_clean["Time_of_Day"] = df_clean["Order_Hour"].apply(time_of_day)

In [56]:
df_clean["Peak_Hour"] = df_clean["Order_Hour"].isin(
    [19, 20, 21]
)

In [57]:
df_clean["Delivery_Performance"] = pd.cut(
    df_clean["Time_taken (min)"],
    bins=[0, 20, 30, 40, 60],
    labels=["Fast", "Normal", "Slow", "Very Slow"]
)

In [58]:
p95 = df_clean["Time_taken (min)"].quantile(0.95)

df_clean["Extreme_Delivery"] = (
    df_clean["Time_taken (min)"] >= p95
)

In [59]:
df_clean.to_csv(
    "zomato_food_delivery_final_cleaned.csv",
    index=False
)

In [60]:
df_clean.to_excel(
    "zomato_food_delivery_final_cleaned.xlsx",
    index=False
)

In [61]:
df_clean["Time_Orderd"] = df_clean["Time_Orderd"].replace(
    "0.833333333", np.nan
)

df_clean["Time_Order_picked"] = df_clean["Time_Order_picked"].replace(
    "0.833333333", np.nan
)

In [62]:
df_clean.to_csv(
    "zomato_food_delivery_final_cleaned.csv",
    index=False
)